name: octal
description: Converts an octal number to its decimal equivalent.
version: 1.0.0
repository: https://github.com/wdestroier/octal

environment:
  sdk: ^3.3.4

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
